[package]
name = "cs3211_assignment_3"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
rand_chacha = "0.3.1"
rand_xoshiro = "0.6.0"
tokio = { version = "1.36.0", features = ["full"] }
